import { collection, addDoc, getDocs, query, where } from "firebase/firestore";
import { db } from "../firebase";

// Categories to add
const categories = [
  { name: "حلويات شرقية" },
  { name: "قوالب كيك" },
  { name: "كيك وكاسات" },
  { name: "كريبات" },
];

// Products data structured from the markdown file
const products = [
  // حلويات شرقية / بالكيلو
  {
    name: "بقلاوة ملوكي",
    price: 75,
    origin: "حلويات شرقية",
    description: "بقلاوة ملوكي فاخرة بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["عجين، سمنة، مكسرات، قطر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: true,
    visible: true,
  },
  {
    name: "بثلاوة فستق حلبي",
    price: 65,
    origin: "حلويات شرقية",
    description: "بثلاوة بالفستق الحلبي الفاخر بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["عجين، فستق حلبي، سمنة، قطر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: true,
    visible: true,
  },
  {
    name: "بقلاوة كاشو",
    price: 40,
    origin: "حلويات شرقية",
    description: "بقلاوة بالكاشو بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["عجين، كاشو، سمنة، قطر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "علبة مشكل",
    price: 100,
    origin: "حلويات شرقية",
    description: "علبة حلويات شرقية متنوعة بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["مشكل حلويات شرقية"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: true,
    visible: true,
  },
  {
    name: "بورما حلبي رفيع",
    price: 70,
    origin: "حلويات شرقية",
    description: "بورما حلبي رفيع بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["عجين، مكسرات حلبية، سمنة، قطر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "بقلاوة حلبي تركي",
    price: 60,
    origin: "حلويات شرقية",
    description: "بقلاوة حلبي تركي فاخرة بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["عجين، مكسرات حلبية، سمنة، قطر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "بقلاوة جوز تركي",
    price: 35,
    origin: "حلويات شرقية",
    description: "بقلاوة بالجوز التركي بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["عجين، جوز، سمنة، قطر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "أصابع جوز",
    price: 35,
    origin: "حلويات شرقية",
    description: "أصابع محشية بالجوز بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["عجين، جوز، سمنة، قطر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "أصابع كستر",
    price: 45,
    origin: "حلويات شرقية",
    description: "أصابع محشية بالكستر بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["عجين، كستر، سمنة، قطر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "شفايف كستر",
    price: 45,
    origin: "حلويات شرقية",
    description: "شفايف محشية بالكستر بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["عجين، كستر، سمنة، قطر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "كلاج قشطة",
    price: 30,
    origin: "حلويات شرقية",
    description: "كلاج بالقشطة الطازجة بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["عجين، قشطة، سمنة، قطر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "كلاج جبنة",
    price: 40,
    origin: "حلويات شرقية",
    description: "كلاج بالجبنة بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["عجين، جبنة، سمنة، قطر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "كلاز بلدي بالجبنة",
    price: 40,
    origin: "حلويات شرقية",
    description: "كلاز بلدي بالجبنة بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["عجين، جبنة، سمنة، قطر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "بلوريا",
    price: 80,
    origin: "حلويات شرقية",
    description: "بلوريا فاخرة بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["عجين، مكسرات، سمنة، قطر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "مكشوفة مكسرات",
    price: 80,
    origin: "حلويات شرقية",
    description: "مكشوفة بالمكسرات الفاخرة بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["عجين، مكسرات، سمنة، قطر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "نمورة",
    price: 25,
    origin: "حلويات شرقية",
    description: "نمورة طرية بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["سميد، سمنة، حليب، قطر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "غريبة",
    price: 10,
    origin: "حلويات شرقية",
    description: "غريبة هشة ولذيذة",
    unit: "علبة",
    weight: "350",
    ingredients: ["طحين، سمنة، سكر، فستق"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "برازق",
    price: 10,
    origin: "حلويات شرقية",
    description: "برازق بالسمسم",
    unit: "علبة",
    weight: "350",
    ingredients: ["طحين، سمسم، سمنة، سكر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "حلاوة الجبن",
    price: 45,
    origin: "حلويات شرقية",
    description: "حلاوة الجبن الطازجة بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["جبنة، سكر، قشطة، فستق"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "مدلوقة",
    price: 40,
    origin: "حلويات شرقية",
    description: "مدلوقة طازجة بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["جبنة، قطر، قشطة"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "كنافة ناعمة",
    price: 40,
    origin: "حلويات شرقية",
    description: "كنافة ناعمة بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["كنافة، جبنة، سمنة، قطر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: true,
    visible: true,
  },
  {
    name: "منافة خشنة",
    price: 40,
    origin: "حلويات شرقية",
    description: "كنافة خشنة بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["كنافة، جبنة، سمنة، قطر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: true,
    visible: true,
  },
  {
    name: "كنافة اسطنبولية",
    price: 45,
    origin: "حلويات شرقية",
    description: "كنافة اسطنبولية فاخرة بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["كنافة، جبنة، فستق، سمنة، قطر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: true,
    visible: true,
  },
  {
    name: "قطايف جوز",
    price: 40,
    origin: "حلويات شرقية",
    description: "قطايف محشية جوز بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["عجين قطايف، جوز، سمنة، قطر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "قطايف جبنة",
    price: 40,
    origin: "حلويات شرقية",
    description: "قطايف محشية جبنة بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["عجين قطايف، جبنة، سمنة، قطر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "قطايف نوتيلا",
    price: 15,
    origin: "حلويات شرقية",
    description: "قطايف محشية نوتيلا",
    unit: "علبة",
    weight: "350",
    ingredients: ["عجين قطايف، نوتيلا"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: true,
    visible: true,
  },
  {
    name: "عش البلبل مكسرات",
    price: 90,
    origin: "حلويات شرقية",
    description: "عش البلبل بالمكسرات الفاخرة بالكيلو",
    unit: "كيلو",
    weight: "1000",
    ingredients: ["كنافة، مكسرات، سمنة، قطر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: true,
    visible: true,
  },
  {
    name: "عش البلبل نوتيلا وبستاشيو",
    price: 20,
    origin: "حلويات شرقية",
    description: "عش البلبل بالنوتيلا والبستاشيو",
    unit: "علبة",
    weight: "350",
    ingredients: ["كنافة، نوتيلا، بستاشيو، سمنة"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: true,
    visible: true,
  },

  // قوالب كيك
  {
    name: "قالب كيك",
    price: 0,
    origin: "قوالب كيك",
    description: "قالب كيك بنكهات فانيلا أو شوكولاتة مع إمكانية إضافة حشوات مجانية ومدفوعة",
    unit: "قالب",
    ingredients: ["دقيق، بيض، سكر، زبدة، حليب"],
    hasVariants: true,
    variants: [
      { size: "صغير - 8 قطع", price: 40 },
      { size: "وسط - 16 قطعة", price: 60 },
      { size: "كبير - 28 قطعة", price: 100 },
    ],
    hasFillings: true,
    freeFillings: ["بلوبيري", "كراميل"],
    paidFillings: [
      { name: "فواكه", smallPrice: 10, largePrice: 20 },
      { name: "أوريو", smallPrice: 10, largePrice: 20 },
      { name: "نوتيلا", smallPrice: 10, largePrice: 20 },
    ],
    featured: true,
    visible: true,
  },
  {
    name: "تشيز كيك",
    price: 0,
    origin: "قوالب كيك",
    description: "تشيز كيك كريمي ولذيذ",
    unit: "قالب",
    ingredients: ["جبنة كريمية، بسكويت، سكر، بيض"],
    hasVariants: true,
    variants: [
      { size: "صغير", price: 40 },
      { size: "وسط", price: 60 },
    ],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: true,
    visible: true,
  },
  {
    name: "تشيز كيك بستاشيو",
    price: 0,
    origin: "قوالب كيك",
    description: "تشيز كيك بالبستاشيو الفاخر",
    unit: "قالب",
    ingredients: ["جبنة كريمية، بستاشيو، بسكويت، سكر"],
    hasVariants: true,
    variants: [
      { size: "صغير", price: 50 },
      { size: "وسط", price: 80 },
    ],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: true,
    visible: true,
  },
  {
    name: "قالب تشوكليت موس",
    price: 0,
    origin: "قوالب كيك",
    description: "قالب تشوكليت موس كريمي",
    unit: "قالب",
    ingredients: ["شوكولاتة، كريمة، بيض، سكر"],
    hasVariants: true,
    variants: [
      { size: "صغير", price: 40 },
      { size: "وسط", price: 60 },
    ],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },

  // كيك وكاسات
  {
    name: "ترليتشا تركية",
    price: 5,
    origin: "كيك وكاسات",
    description: "ترليتشا تركية أصلية",
    unit: "حبة",
    ingredients: ["حليب، بسكويت، كاكاو، كريمة"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "سان سيباستيان",
    price: 20,
    origin: "كيك وكاسات",
    description: "كيك سان سيباستيان الشهير",
    unit: "حبة",
    ingredients: ["جبنة كريمية، بيض، سكر، دقيق"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: true,
    visible: true,
  },
  {
    name: "تشيز كيك ميني",
    price: 10,
    origin: "كيك وكاسات",
    description: "تشيز كيك ميني بحجم مثالي",
    unit: "حبة",
    ingredients: ["جبنة كريمية، بسكويت، سكر"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "تشيز كيك كاسة",
    price: 0,
    origin: "كيك وكاسات",
    description: "تشيز كيك في كاسة",
    unit: "كاسة",
    ingredients: ["جبنة كريمية، بسكويت، سكر"],
    hasVariants: true,
    variants: [
      { size: "صغير - حبتين", price: 2 },
      { size: "كبير", price: 5 },
    ],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "قشطوطة - ميكس شوكولاتة",
    price: 8,
    origin: "كيك وكاسات",
    description: "قشطوطة بميكس الشوكولاتة",
    unit: "حبة",
    ingredients: ["قشطة، شوكولاتة، بسكويت"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "سوفليه",
    price: 15,
    origin: "كيك وكاسات",
    description: "سوفليه شوكولاتة ساخن",
    unit: "حبة",
    ingredients: ["شوكولاتة، بيض، زبدة، سكر، دقيق"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: true,
    visible: true,
  },
  {
    name: "بودينج",
    price: 5,
    origin: "كيك وكاسات",
    description: "بودينج كريمي",
    unit: "كاسة",
    ingredients: ["حليب، نشا، سكر، فانيلا"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "ترند دبي",
    price: 12,
    origin: "كيك وكاسات",
    description: "كيكة ترند دبي الشهيرة",
    unit: "حبة",
    ingredients: ["شوكولاتة، فستق، كريمة"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: true,
    visible: true,
  },
  {
    name: "تيريميسو",
    price: 10,
    origin: "كيك وكاسات",
    description: "تيريميسو إيطالي أصلي",
    unit: "حبة",
    ingredients: ["بسكويت، قهوة، جبنة ماسكاربوني، كاكاو"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: true,
    visible: true,
  },
  {
    name: "سجادة",
    price: 5,
    origin: "كيك وكاسات",
    description: "سجادة شوكولاتة",
    unit: "حبة",
    ingredients: ["شوكولاتة، بسكويت، كريمة"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "ريد فيلفيت",
    price: 12,
    origin: "كيك وكاسات",
    description: "كيك ريد فيلفيت الأحمر المخملي",
    unit: "حبة",
    ingredients: ["دقيق، كاكاو، ملون طعام أحمر، جبنة كريمية"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: true,
    visible: true,
  },

  // كريبات
  {
    name: "كريب",
    price: 15,
    origin: "كريبات",
    description: "كريب بحشوات متنوعة",
    unit: "حبة",
    ingredients: ["دقيق، بيض، حليب، حشوات"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
  {
    name: "فشافيش",
    price: 12,
    origin: "كريبات",
    description: "فشافيش كريب (8 حبات)",
    unit: "علبة",
    size: "8 حبات",
    ingredients: ["دقيق، بيض، حليب، حشوات"],
    hasVariants: false,
    variants: [],
    hasFillings: false,
    freeFillings: [],
    paidFillings: [],
    featured: false,
    visible: true,
  },
];

export async function seedCategories() {
  try {
    console.log("Starting to seed categories...");
    const categoriesRef = collection(db, "categories");

    for (const category of categories) {
      // Check if category already exists
      const q = query(categoriesRef, where("name", "==", category.name));
      const querySnapshot = await getDocs(q);

      if (querySnapshot.empty) {
        await addDoc(categoriesRef, category);
        console.log(`Added category: ${category.name}`);
      } else {
        console.log(`Category already exists: ${category.name}`);
      }
    }

    console.log("Categories seeding completed!");
    return { success: true, message: "تم إضافة الفئات بنجاح" };
  } catch (error) {
    console.error("Error seeding categories:", error);
    return { success: false, message: error.message };
  }
}

export async function seedProducts() {
  try {
    console.log("Starting to seed products...");
    const productsRef = collection(db, "products");

    for (const product of products) {
      // Check if product already exists
      const q = query(productsRef, where("name", "==", product.name));
      const querySnapshot = await getDocs(q);

      if (querySnapshot.empty) {
        // Add placeholder images (to be replaced manually)
        const productWithImages = {
          ...product,
          mainImage:
            "https://via.placeholder.com/400x400?text=" +
            encodeURIComponent(product.name),
          images: [
            "https://via.placeholder.com/400x400?text=Image+1",
            "https://via.placeholder.com/400x400?text=Image+2",
          ],
        };

        await addDoc(productsRef, productWithImages);
        console.log(`Added product: ${product.name}`);
      } else {
        console.log(`Product already exists: ${product.name}`);
      }
    }

    console.log("Products seeding completed!");
    return { success: true, message: "تم إضافة المنتجات بنجاح" };
  } catch (error) {
    console.error("Error seeding products:", error);
    return { success: false, message: error.message };
  }
}

export async function seedAll() {
  const categoriesResult = await seedCategories();
  if (!categoriesResult.success) {
    return categoriesResult;
  }

  const productsResult = await seedProducts();
  return productsResult;
}
